# Generated by Django 2.2.5 on 2019-09-18 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='who_disliked',
        ),
        migrations.RemoveField(
            model_name='article',
            name='who_liked',
        ),
    ]
