# Generated by Django 2.2.5 on 2019-09-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20190919_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='last_edited',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
