# Generated by Django 2.2.5 on 2019-09-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_related_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='related_area',
            field=models.CharField(choices=[('sport', 'Sport'), ('social', 'Social'), ('science', 'Science'), ('cyber security', 'Cyber Security'), ('health', 'Health'), ('political', 'Political'), ('magazin', 'Magazin')], max_length=25, null=True),
        ),
    ]
