# Generated by Django 2.2.5 on 2019-09-20 18:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190919_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='https://www.eguardtech.com/wp-content/uploads/2018/08/Network-Profile.png', null=True, upload_to=accounts.models.upload_to),
        ),
    ]
