# Generated by Django 2.2.5 on 2019-09-22 09:57

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190920_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='media/defaults/avatar.png', null=True, upload_to=accounts.models.upload_to),
        ),
    ]
