# Generated by Django 2.2.5 on 2019-09-22 09:58

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190922_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='defaults/avatar.png', null=True, upload_to=accounts.models.upload_to),
        ),
    ]
